package com.xemophon.aljabr.ui.theme

import androidx.compose.ui.graphics.Color

// Default Purple Theme (Material 3 Defaults)
val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)
val Purple40 = Color(0xFF6650A4)
val PurpleGrey40 = Color(0xFF625B71)
val Pink40 = Color(0xFF7D5260)

// Calculator specific colors - Light
val CalcButtonStandardLight = Color(0xFFE2E2E6)
val CalcButtonOperationLight = Color(0xFFEADDFF)
val CalcButtonEqualLight = Color(0xFFFFD8E4)
val CalcContainerBackgroundLight = Color(0xFFF1F0F4)
val CalcPrimaryFixedDimLight = Color(0xFFDDE2F9)

// Calculator specific colors - Dark
val CalcButtonStandardDark = Color(0xFF44474E)
val CalcButtonOperationDark = Color(0xFF4F378B)
val CalcButtonEqualDark = Color(0xFF633B48)
val CalcContainerBackgroundDark = Color(0xFF1B1B1F)
val CalcPrimaryFixedDimDark = Color(0xFF404659)

// --- Blue Theme ---
// Light
val BluePrimaryLight = Color(0xFF005AC1)
val BlueOnPrimaryLight = Color(0xFFFFFFFF)
val BluePrimaryContainerLight = Color(0xFFC2D8FF)
val BlueOnPrimaryContainerLight = Color(0xFF001A41)
val BlueSecondaryLight = Color(0xFF535E78)
val BlueOnSecondaryLight = Color(0xFFFFFFFF)
val BlueSecondaryContainerLight = Color(0xFFE0E8F8)
val BlueOnSecondaryContainerLight = Color(0xFF0F1B32)
val BlueTertiaryLight = Color(0xFF3B5E8C)
val BlueOnTertiaryLight = Color(0xFFFFFFFF)
val BlueTertiaryContainerLight = Color(0xFFD2E4FF)
val BlueOnTertiaryContainerLight = Color(0xFF001D36)
val BlueSurfaceLight = Color(0xFFF8FAFF)
val BlueOnSurfaceLight = Color(0xFF191C20)
val BlueSurfaceVariantLight = Color(0xFFE0E2EC)
val BlueOnSurfaceVariantLight = Color(0xFF43474E)
val BlueOutlineLight = Color(0xFF74777F)
val BlueInversePrimaryLight = Color(0xFFADC6FF)
val BlueInverseSurfaceLight = Color(0xFF2E3036)
val BlueInverseOnSurfaceLight = Color(0xFFF0F0F7)

// Dark
val BluePrimaryDark = Color(0xFFADC6FF)
val BlueOnPrimaryDark = Color(0xFF002E69)
val BluePrimaryContainerDark = Color(0xFF004494)
val BlueOnPrimaryContainerDark = Color(0xFFD8E2FF)
val BlueSecondaryDark = Color(0xFFBBC6E4)
val BlueOnSecondaryDark = Color(0xFF253048)
val BlueSecondaryContainerDark = Color(0xFF2A364F)
val BlueOnSecondaryContainerDark = Color(0xFFD0DCFC)
val BlueTertiaryDark = Color(0xFF9ECBFF)
val BlueOnTertiaryDark = Color(0xFF00325A)
val BlueTertiaryContainerDark = Color(0xFF1A3B5C)
val BlueOnTertiaryContainerDark = Color(0xFFCDE5FF)
val BlueSurfaceDark = Color(0xFF111318)
val BlueOnSurfaceDark = Color(0xFFE1E2E8)
val BlueSurfaceVariantDark = Color(0xFF43474E)
val BlueOnSurfaceVariantDark = Color(0xFFC3C6CF)
val BlueOutlineDark = Color(0xFF8D9199)
val BlueInversePrimaryDark = Color(0xFF005AC1)
val BlueInverseSurfaceDark = Color(0xFFE1E2E8)
val BlueInverseOnSurfaceDark = Color(0xFF191C20)

// --- Green Theme ---
// Light
val GreenPrimaryLight = Color(0xFF006D3B)
val GreenOnPrimaryLight = Color(0xFFFFFFFF)
val GreenPrimaryContainerLight = Color(0xFF82ECA3)
val GreenOnPrimaryContainerLight = Color(0xFF00210E)
val GreenSecondaryLight = Color(0xFF4F6354)
val GreenOnSecondaryLight = Color(0xFFFFFFFF)
val GreenSecondaryContainerLight = Color(0xFFCCE8D2)
val GreenOnSecondaryContainerLight = Color(0xFF0D1F13)
val GreenTertiaryLight = Color(0xFF286A55)
val GreenOnTertiaryLight = Color(0xFFFFFFFF)
val GreenTertiaryContainerLight = Color(0xFFB6EEDC)
val GreenOnTertiaryContainerLight = Color(0xFF002018)
val GreenSurfaceLight = Color(0xFFF6FBF6)
val GreenOnSurfaceLight = Color(0xFF181D19)
val GreenSurfaceVariantLight = Color(0xFFDCE5DC)
val GreenOnSurfaceVariantLight = Color(0xFF404942)
val GreenOutlineLight = Color(0xFF707972)
val GreenInversePrimaryLight = Color(0xFF80D999)
val GreenInverseSurfaceLight = Color(0xFF2C322D)
val GreenInverseOnSurfaceLight = Color(0xFFEFF2EC)

// Dark
val GreenPrimaryDark = Color(0xFF80D999)
val GreenOnPrimaryDark = Color(0xFF00391C)
val GreenPrimaryContainerDark = Color(0xFF00522B)
val GreenOnPrimaryContainerDark = Color(0xFF9BF6B4)
val GreenSecondaryDark = Color(0xFFB7CCBA)
val GreenOnSecondaryDark = Color(0xFF213527)
val GreenSecondaryContainerDark = Color(0xFF253B2B)
val GreenOnSecondaryContainerDark = Color(0xFFCDE4D0)
val GreenTertiaryDark = Color(0xFF98D1C0)
val GreenOnTertiaryDark = Color(0xFF00382B)
val GreenTertiaryContainerDark = Color(0xFF104A3A)
val GreenOnTertiaryContainerDark = Color(0xFFA3F2D9)
val GreenSurfaceDark = Color(0xFF101511)
val GreenOnSurfaceDark = Color(0xFFE0E4DE)
val GreenSurfaceVariantDark = Color(0xFF404942)
val GreenOnSurfaceVariantDark = Color(0xFFC0C9C0)
val GreenOutlineDark = Color(0xFF8A938B)
val GreenInversePrimaryDark = Color(0xFF006D3B)
val GreenInverseSurfaceDark = Color(0xFFE0E4DE)
val GreenInverseOnSurfaceDark = Color(0xFF181D19)

// --- Red Theme ---
// Light
val RedPrimaryLight = Color(0xFFBA1A1A)
val RedOnPrimaryLight = Color(0xFFFFFFFF)
val RedPrimaryContainerLight = Color(0xFFFFB4AB)
val RedOnPrimaryContainerLight = Color(0xFF410002)
val RedSecondaryLight = Color(0xFF775652)
val RedOnSecondaryLight = Color(0xFFFFFFFF)
val RedSecondaryContainerLight = Color(0xFFF5E0DD)
val RedOnSecondaryContainerLight = Color(0xFF2C1512)
val RedTertiaryLight = Color(0xFF903A32)
val RedOnTertiaryLight = Color(0xFFFFFFFF)
val RedTertiaryContainerLight = Color(0xFFFFD8D0)
val RedOnTertiaryContainerLight = Color(0xFF3A0B06)
val RedSurfaceLight = Color(0xFFFFF8F7)
val RedOnSurfaceLight = Color(0xFF231918)
val RedSurfaceVariantLight = Color(0xFFF5DDDA)
val RedOnSurfaceVariantLight = Color(0xFF534341)
val RedOutlineLight = Color(0xFF857371)
val RedInversePrimaryLight = Color(0xFFFFB4AB)
val RedInverseSurfaceLight = Color(0xFF382D2C)
val RedInverseOnSurfaceLight = Color(0xFFFCEEEB)

// Dark
val RedPrimaryDark = Color(0xFFFFB4AB)
val RedOnPrimaryDark = Color(0xFF690005)
val RedPrimaryContainerDark = Color(0xFF93000A)
val RedOnPrimaryContainerDark = Color(0xFFFFDAD6)
val RedSecondaryDark = Color(0xFFE7BDB8)
val RedOnSecondaryDark = Color(0xFF442926)
val RedSecondaryContainerDark = Color(0xFF4A2F2B)
val RedOnSecondaryContainerDark = Color(0xFFFADBD6)
val RedTertiaryDark = Color(0xFFFFB3A7)
val RedOnTertiaryDark = Color(0xFF561D18)
val RedTertiaryContainerDark = Color(0xFF60231D)
val RedOnTertiaryContainerDark = Color(0xFFFFDAD4)
val RedSurfaceDark = Color(0xFF1A1111)
val RedOnSurfaceDark = Color(0xFFF1DFDC)
val RedSurfaceVariantDark = Color(0xFF534341)
val RedOnSurfaceVariantDark = Color(0xFFD8C2BF)
val RedOutlineDark = Color(0xFFA08C8A)
val RedInversePrimaryDark = Color(0xFFBA1A1A)
val RedInverseSurfaceDark = Color(0xFFF1DFDC)
val RedInverseOnSurfaceDark = Color(0xFF231918)

// --- Yellow Theme ---
// Light
val YellowPrimaryLight = Color(0xFF685F00)
val YellowOnPrimaryLight = Color(0xFFFFFFFF)
val YellowPrimaryContainerLight = Color(0xFFFBE455)
val YellowOnPrimaryContainerLight = Color(0xFF1E1C00)
val YellowSecondaryLight = Color(0xFF646042)
val YellowOnSecondaryLight = Color(0xFFFFFFFF)
val YellowSecondaryContainerLight = Color(0xFFF1EAC4)
val YellowOnSecondaryContainerLight = Color(0xFF1F1C05)
val YellowTertiaryLight = Color(0xFF6D5D00)
val YellowOnTertiaryLight = Color(0xFFFFFFFF)
val YellowTertiaryContainerLight = Color(0xFFF6E8A6)
val YellowOnTertiaryContainerLight = Color(0xFF221B00)
val YellowSurfaceLight = Color(0xFFFFFBF0)
val YellowOnSurfaceLight = Color(0xFF1D1B13)
val YellowSurfaceVariantLight = Color(0xFFE8E2D0)
val YellowOnSurfaceVariantLight = Color(0xFF4A4739)
val YellowOutlineLight = Color(0xFF7B7767)
val YellowInversePrimaryLight = Color(0xFFDAC950)
val YellowInverseSurfaceLight = Color(0xFF323028)
val YellowInverseOnSurfaceLight = Color(0xFFF7F0E5)

// Dark
val YellowPrimaryDark = Color(0xFFDAC950)
val YellowOnPrimaryDark = Color(0xFF363100)
val YellowPrimaryContainerDark = Color(0xFF524B00)
val YellowOnPrimaryContainerDark = Color(0xFFF7E569)
val YellowSecondaryDark = Color(0xFFCEC8A4)
val YellowOnSecondaryDark = Color(0xFF353118)
val YellowSecondaryContainerDark = Color(0xFF3A351E)
val YellowOnSecondaryContainerDark = Color(0xFFECE5BC)
val YellowTertiaryDark = Color(0xFFE5CB4B)
val YellowOnTertiaryDark = Color(0xFF393000)
val YellowTertiaryContainerDark = Color(0xFF4D4000)
val YellowOnTertiaryContainerDark = Color(0xFFFBE37B)
val YellowSurfaceDark = Color(0xFF14130B)
val YellowOnSurfaceDark = Color(0xFFE8E2D5)
val YellowSurfaceVariantDark = Color(0xFF4A4739)
val YellowOnSurfaceVariantDark = Color(0xFFCCC6B5)
val YellowOutlineDark = Color(0xFF959181)
val YellowInversePrimaryDark = Color(0xFF685F00)
val YellowInverseSurfaceDark = Color(0xFFE8E2D5)
val YellowInverseOnSurfaceDark = Color(0xFF1D1B13)

// --- Orange Theme ---
// Light
val OrangePrimaryLight = Color(0xFF8B5000)
val OrangeOnPrimaryLight = Color(0xFFFFFFFF)
val OrangePrimaryContainerLight = Color(0xFFFFB77C)
val OrangeOnPrimaryContainerLight = Color(0xFF2E1500)
val OrangeSecondaryLight = Color(0xFF755846)
val OrangeOnSecondaryLight = Color(0xFFFFFFFF)
val OrangeSecondaryContainerLight = Color(0xFFF7E2D4)
val OrangeOnSecondaryContainerLight = Color(0xFF2B1609)
val OrangeTertiaryLight = Color(0xFF8C4A00)
val OrangeOnTertiaryLight = Color(0xFFFFFFFF)
val OrangeTertiaryContainerLight = Color(0xFFFFD7BF)
val OrangeOnTertiaryContainerLight = Color(0xFF351000)
val OrangeSurfaceLight = Color(0xFFFFF8F5)
val OrangeOnSurfaceLight = Color(0xFF221A14)
val OrangeSurfaceVariantLight = Color(0xFFF4DFD3)
val OrangeOnSurfaceVariantLight = Color(0xFF52443C)
val OrangeOutlineLight = Color(0xFF85746B)
val OrangeInversePrimaryLight = Color(0xFFFFB77C)
val OrangeInverseSurfaceLight = Color(0xFF382E28)
val OrangeInverseOnSurfaceLight = Color(0xFFFFEEE5)

// Dark
val OrangePrimaryDark = Color(0xFFFFB77C)
val OrangeOnPrimaryDark = Color(0xFF4A2800)
val OrangePrimaryContainerDark = Color(0xFF693C00)
val OrangeOnPrimaryContainerDark = Color(0xFFFFDCC2)
val OrangeSecondaryDark = Color(0xFFE5C0AB)
val OrangeOnSecondaryDark = Color(0xFF422B1C)
val OrangeSecondaryContainerDark = Color(0xFF452E20)
val OrangeOnSecondaryContainerDark = Color(0xFFFADECE)
val OrangeTertiaryDark = Color(0xFFFFB68C)
val OrangeOnTertiaryDark = Color(0xFF4B2500)
val OrangeTertiaryContainerDark = Color(0xFF562A00)
val OrangeOnTertiaryContainerDark = Color(0xFFFFDCBE)
val OrangeSurfaceDark = Color(0xFF19120C)
val OrangeOnSurfaceDark = Color(0xFFF0DFD7)
val OrangeSurfaceVariantDark = Color(0xFF52443C)
val OrangeOnSurfaceVariantDark = Color(0xFFD7C3B7)
val OrangeOutlineDark = Color(0xFFA08D83)
val OrangeInversePrimaryDark = Color(0xFF8B5000)
val OrangeInverseSurfaceDark = Color(0xFFF0DFD7)
val OrangeInverseOnSurfaceDark = Color(0xFF221A14)

// --- Teal Theme ---
// Light
val TealPrimaryLight = Color(0xFF006A6A)
val TealOnPrimaryLight = Color(0xFFFFFFFF)
val TealPrimaryContainerLight = Color(0xFF80E5E4)
val TealOnPrimaryContainerLight = Color(0xFF002020)
val TealSecondaryLight = Color(0xFF4A6363)
val TealOnSecondaryLight = Color(0xFFFFFFFF)
val TealSecondaryContainerLight = Color(0xFFC8E5E4)
val TealOnSecondaryContainerLight = Color(0xFF051F1F)
val TealTertiaryLight = Color(0xFF006B67)
val TealOnTertiaryLight = Color(0xFFFFFFFF)
val TealTertiaryContainerLight = Color(0xFFB1ECE9)
val TealOnTertiaryContainerLight = Color(0xFF002020)
val TealSurfaceLight = Color(0xFFF4FAFA)
val TealOnSurfaceLight = Color(0xFF161D1D)
val TealSurfaceVariantLight = Color(0xFFDAE5E4)
val TealOnSurfaceVariantLight = Color(0xFF3F4948)
val TealOutlineLight = Color(0xFF6F7979)
val TealInversePrimaryLight = Color(0xFF80D5D4)
val TealInverseSurfaceLight = Color(0xFF2B3131)
val TealInverseOnSurfaceLight = Color(0xFFECF2F1)

// Dark
val TealPrimaryDark = Color(0xFF80D5D4)
val TealOnPrimaryDark = Color(0xFF003737)
val TealPrimaryContainerDark = Color(0xFF004F4F)
val TealOnPrimaryContainerDark = Color(0xFF9CF1F0)
val TealSecondaryDark = Color(0xFFB0CCCB)
val TealOnSecondaryDark = Color(0xFF1B3534)
val TealSecondaryContainerDark = Color(0xFF223A39)
val TealOnSecondaryContainerDark = Color(0xFFC4E4E3)
val TealTertiaryDark = Color(0xFF7AD6D2)
val TealOnTertiaryDark = Color(0xFF003735)
val TealTertiaryContainerDark = Color(0xFF004D4A)
val TealOnTertiaryContainerDark = Color(0xFF96F2EE)
val TealSurfaceDark = Color(0xFF0E1415)
val TealOnSurfaceDark = Color(0xFFE0E3E3)
val TealSurfaceVariantDark = Color(0xFF3F4948)
val TealOnSurfaceVariantDark = Color(0xFFBEC9C8)
val TealOutlineDark = Color(0xFF889392)
val TealInversePrimaryDark = Color(0xFF006A6A)
val TealInverseSurfaceDark = Color(0xFFE0E3E3)
val TealInverseOnSurfaceDark = Color(0xFF161D1D)

// --- Pink Theme ---
// Light
val PinkPrimaryLight = Color(0xFF984061)
val PinkOnPrimaryLight = Color(0xFFFFFFFF)
val PinkPrimaryContainerLight = Color(0xFFFFB0C8)
val PinkOnPrimaryContainerLight = Color(0xFF3E001D)
val PinkSecondaryLight = Color(0xFF74565F)
val PinkOnSecondaryLight = Color(0xFFFFFFFF)
val PinkSecondaryContainerLight = Color(0xFFF5E0E5)
val PinkOnSecondaryContainerLight = Color(0xFF2B151C)
val PinkTertiaryLight = Color(0xFF923B6C)
val PinkOnTertiaryLight = Color(0xFFFFFFFF)
val PinkTertiaryContainerLight = Color(0xFFFFD8EE)
val PinkOnTertiaryContainerLight = Color(0xFF3B082A)
val PinkSurfaceLight = Color(0xFFFFF8F8)
val PinkOnSurfaceLight = Color(0xFF201A1B)
val PinkSurfaceVariantLight = Color(0xFFF2DDE1)
val PinkOnSurfaceVariantLight = Color(0xFF514347)
val PinkOutlineLight = Color(0xFF837377)
val PinkInversePrimaryLight = Color(0xFFFFB0C8)
val PinkInverseSurfaceLight = Color(0xFF362E30)
val PinkInverseOnSurfaceLight = Color(0xFFFAEEEE)

// Dark
val PinkPrimaryDark = Color(0xFFFFB0C8)
val PinkOnPrimaryDark = Color(0xFF5E1133)
val PinkPrimaryContainerDark = Color(0xFF7B2949)
val PinkOnPrimaryContainerDark = Color(0xFFFFD9E2)
val PinkSecondaryDark = Color(0xFFE2BDC6)
val PinkOnSecondaryDark = Color(0xFF422931)
val PinkSecondaryContainerDark = Color(0xFF462C34)
val PinkOnSecondaryContainerDark = Color(0xFFFAD7DF)
val PinkTertiaryDark = Color(0xFFFFAFD8)
val PinkOnTertiaryDark = Color(0xFF5A0B3D)
val PinkTertiaryContainerDark = Color(0xFF5E1E3F)
val PinkOnTertiaryContainerDark = Color(0xFFFFD7ED)
val PinkSurfaceDark = Color(0xFF181113)
val PinkOnSurfaceDark = Color(0xFFECE0E1)
val PinkSurfaceVariantDark = Color(0xFF514347)
val PinkOnSurfaceVariantDark = Color(0xFFD5C2C6)
val PinkOutlineDark = Color(0xFF9E8C90)
val PinkInversePrimaryDark = Color(0xFF984061)
val PinkInverseSurfaceDark = Color(0xFFECE0E1)
val PinkInverseOnSurfaceDark = Color(0xFF201A1B)

// --- Brown Theme ---
// Light
val BrownPrimaryLight = Color(0xFF7A5930)
val BrownOnPrimaryLight = Color(0xFFFFFFFF)
val BrownPrimaryContainerLight = Color(0xFFE3C3A1)
val BrownOnPrimaryContainerLight = Color(0xFF2A1700)
val BrownSecondaryLight = Color(0xFF6C5D4F)
val BrownOnSecondaryLight = Color(0xFFFFFFFF)
val BrownSecondaryContainerLight = Color(0xFFEFE2D5)
val BrownOnSecondaryContainerLight = Color(0xFF241A0F)
val BrownTertiaryLight = Color(0xFF825528)
val BrownOnTertiaryLight = Color(0xFFFFFFFF)
val BrownTertiaryContainerLight = Color(0xFFECD8C1)
val BrownOnTertiaryContainerLight = Color(0xFF2B1705)
val BrownSurfaceLight = Color(0xFFFFF8F5)
val BrownOnSurfaceLight = Color(0xFF201B17)
val BrownSurfaceVariantLight = Color(0xFFF0E0D2)
val BrownOnSurfaceVariantLight = Color(0xFF4F453B)
val BrownOutlineLight = Color(0xFF81756A)
val BrownInversePrimaryLight = Color(0xFFECBE91)
val BrownInverseSurfaceLight = Color(0xFF362F2B)
val BrownInverseOnSurfaceLight = Color(0xFFFAEEE8)

// Dark
val BrownPrimaryDark = Color(0xFFECBE91)
val BrownOnPrimaryDark = Color(0xFF462A06)
val BrownPrimaryContainerDark = Color(0xFF60411B)
val BrownOnPrimaryContainerDark = Color(0xFFFFDCC1)
val BrownSecondaryDark = Color(0xFFD9C4B3)
val BrownOnSecondaryDark = Color(0xFF3B2F23)
val BrownSecondaryContainerDark = Color(0xFF403328)
val BrownOnSecondaryContainerDark = Color(0xFFEADBCB)
val BrownTertiaryDark = Color(0xFFF1BA83)
val BrownOnTertiaryDark = Color(0xFF482902)
val BrownTertiaryContainerDark = Color(0xFF4E3013)
val BrownOnTertiaryContainerDark = Color(0xFFFBDCB9)
val BrownSurfaceDark = Color(0xFF17130F)
val BrownOnSurfaceDark = Color(0xFFECE0DA)
val BrownSurfaceVariantDark = Color(0xFF4F453B)
val BrownOnSurfaceVariantDark = Color(0xFFD3C4B7)
val BrownOutlineDark = Color(0xFF9C8E83)
val BrownInversePrimaryDark = Color(0xFF7A5930)
val BrownInverseSurfaceDark = Color(0xFFECE0DA)
val BrownInverseOnSurfaceDark = Color(0xFF201B17)
