package com.xemophon.aljabr.ui.theme

import androidx.compose.ui.graphics.Color

// Default Purple Theme (Material 3 Defaults)
val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)
val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

// Calculator specific colors - Light (Base for overrides)
val CalcButtonStandardLight = Color(0xFFE2E2E6)
val CalcButtonOperationLight = Color(0xFFD2E4FF)
val CalcButtonEqualLight = Color(0xFFD3E0FF)
val CalcContainerBackgroundLight = Color(0xFFF1F0F4)
val CalcPrimaryFixedDimLight = Color(0xFFDDE2F9)

// Calculator specific colors - Dark (Base for overrides)
val CalcButtonStandardDark = Color(0xFF44474E)
val CalcButtonOperationDark = Color(0xFF00468B)
val CalcButtonEqualDark = Color(0xFF00468B)
val CalcContainerBackgroundDark = Color(0xFF1B1B1F)
val CalcPrimaryFixedDimDark = Color(0xFF404659)

// --- Blue Theme ---
// Light
val BluePrimaryLight = Color(0xFF005AC1)
val BlueOnPrimaryLight = Color(0xFFFFFFFF)
val BluePrimaryContainerLight = Color(0xFFD8E2FF)
val BlueOnPrimaryContainerLight = Color(0xFF001A41)
val BlueSecondaryLight = Color(0xFF535E78)
val BlueOnSecondaryLight = Color(0xFFFFFFFF)
val BlueSecondaryContainerLight = Color(0xFFD8E2FF)
val BlueOnSecondaryContainerLight = Color(0xFF0F1B32)
val BlueTertiaryLight = Color(0xFF6D5676)
val BlueOnTertiaryLight = Color(0xFFFFFFFF)
val BlueTertiaryContainerLight = Color(0xFFF7D8FF)
val BlueOnTertiaryContainerLight = Color(0xFF271430)
val BlueSurfaceLight = Color(0xFFFEFBFF)
val BlueOnSurfaceLight = Color(0xFF1B1B1F)
val BlueSurfaceVariantLight = Color(0xFFE1E2EC)
val BlueOnSurfaceVariantLight = Color(0xFF44474F)
val BlueOutlineLight = Color(0xFF74777F)
val BlueInversePrimaryLight = Color(0xFFADC6FF)
val BlueInverseSurfaceLight = Color(0xFF313033)
val BlueInverseOnSurfaceLight = Color(0xFFF4EFF4)

// Dark
val BluePrimaryDark = Color(0xFFADC6FF)
val BlueOnPrimaryDark = Color(0xFF002E69)
val BluePrimaryContainerDark = Color(0xFF004494)
val BlueOnPrimaryContainerDark = Color(0xFFD8E2FF)
val BlueSecondaryDark = Color(0xFFBBC6E4)
val BlueOnSecondaryDark = Color(0xFF253048)
val BlueSecondaryContainerDark = Color(0xFF3B465F)
val BlueOnSecondaryContainerDark = Color(0xFFD8E2FF)
val BlueTertiaryDark = Color(0xFFD9BDE3)
val BlueOnTertiaryDark = Color(0xFF3D2946)
val BlueTertiaryContainerDark = Color(0xFF543F5E)
val BlueOnTertiaryContainerDark = Color(0xFFF7D8FF)
val BlueSurfaceDark = Color(0xFF1B1B1F)
val BlueOnSurfaceDark = Color(0xFFE3E2E6)
val BlueSurfaceVariantDark = Color(0xFF44474F)
val BlueOnSurfaceVariantDark = Color(0xFFC4C6D0)
val BlueOutlineDark = Color(0xFF8E9099)
val BlueInversePrimaryDark = Color(0xFF005AC1)
val BlueInverseSurfaceDark = Color(0xFFE3E2E6)
val BlueInverseOnSurfaceDark = Color(0xFF1B1B1F)

// --- Green Theme ---
// Light
val GreenPrimaryLight = Color(0xFF006D3B)
val GreenOnPrimaryLight = Color(0xFFFFFFFF)
val GreenPrimaryContainerLight = Color(0xFF9BF6B4)
val GreenOnPrimaryContainerLight = Color(0xFF00210E)
val GreenSecondaryLight = Color(0xFF4F6354)
val GreenOnSecondaryLight = Color(0xFFFFFFFF)
val GreenSecondaryContainerLight = Color(0xFFD2E8D5)
val GreenOnSecondaryContainerLight = Color(0xFF0D1F13)
val GreenTertiaryLight = Color(0xFF3B6470)
val GreenOnTertiaryLight = Color(0xFFFFFFFF)
val GreenTertiaryContainerLight = Color(0xFFBEEAF7)
val GreenOnTertiaryContainerLight = Color(0xFF001F26)
val GreenSurfaceLight = Color(0xFFFBFDF8)
val GreenOnSurfaceLight = Color(0xFF191C1A)
val GreenSurfaceVariantLight = Color(0xFFDCE5DC)
val GreenOnSurfaceVariantLight = Color(0xFF404942)
val GreenOutlineLight = Color(0xFF707972)
val GreenInversePrimaryLight = Color(0xFF80D999)
val GreenInverseSurfaceLight = Color(0xFF2E312E)
val GreenInverseOnSurfaceLight = Color(0xFFF0F1EB)

// Dark
val GreenPrimaryDark = Color(0xFF80D999)
val GreenOnPrimaryDark = Color(0xFF00391C)
val GreenPrimaryContainerDark = Color(0xFF00522B)
val GreenOnPrimaryContainerDark = Color(0xFF9BF6B4)
val GreenSecondaryDark = Color(0xFFB7CCBA)
val GreenOnSecondaryDark = Color(0xFF213527)
val GreenSecondaryContainerDark = Color(0xFF384B3D)
val GreenOnSecondaryContainerDark = Color(0xFFD2E8D5)
val GreenTertiaryDark = Color(0xFFA2CEDC)
val GreenOnTertiaryDark = Color(0xFF003540)
val GreenTertiaryContainerDark = Color(0xFF214C58)
val GreenOnTertiaryContainerDark = Color(0xFFBEEAF7)
val GreenSurfaceDark = Color(0xFF191C1A)
val GreenOnSurfaceDark = Color(0xFFE1E3DF)
val GreenSurfaceVariantDark = Color(0xFF404942)
val GreenOnSurfaceVariantDark = Color(0xFFC0C9C0)
val GreenOutlineDark = Color(0xFF8A938B)
val GreenInversePrimaryDark = Color(0xFF006D3B)
val GreenInverseSurfaceDark = Color(0xFFE1E3DF)
val GreenInverseOnSurfaceDark = Color(0xFF191C1A)

// --- Red Theme ---
// Light
val RedPrimaryLight = Color(0xFFBA1A1A)
val RedOnPrimaryLight = Color(0xFFFFFFFF)
val RedPrimaryContainerLight = Color(0xFFFFDAD6)
val RedOnPrimaryContainerLight = Color(0xFF410002)
val RedSecondaryLight = Color(0xFF775652)
val RedOnSecondaryLight = Color(0xFFFFFFFF)
val RedSecondaryContainerLight = Color(0xFFFFDAD6)
val RedOnSecondaryContainerLight = Color(0xFF2C1512)
val RedTertiaryLight = Color(0xFF715B29)
val RedOnTertiaryLight = Color(0xFFFFFFFF)
val RedTertiaryContainerLight = Color(0xFFFDE0A1)
val RedOnTertiaryContainerLight = Color(0xFF251A00)
val RedSurfaceLight = Color(0xFFFFFBFF)
val RedOnSurfaceLight = Color(0xFF201A19)
val RedSurfaceVariantLight = Color(0xFFF5DDDA)
val RedOnSurfaceVariantLight = Color(0xFF534341)
val RedOutlineLight = Color(0xFF857371)
val RedInversePrimaryLight = Color(0xFFFFB4AB)
val RedInverseSurfaceLight = Color(0xFF362F2E)
val RedInverseOnSurfaceLight = Color(0xFFFBEEEC)

// Dark
val RedPrimaryDark = Color(0xFFFFB4AB)
val RedOnPrimaryDark = Color(0xFF690005)
val RedPrimaryContainerDark = Color(0xFF93000A)
val RedOnPrimaryContainerDark = Color(0xFFFFDAD6)
val RedSecondaryDark = Color(0xFFE7BDB8)
val RedOnSecondaryDark = Color(0xFF442926)
val RedSecondaryContainerDark = Color(0xFF5D3F3C)
val RedOnSecondaryContainerDark = Color(0xFFFFDAD6)
val RedTertiaryDark = Color(0xFFE0C38C)
val RedOnTertiaryDark = Color(0xFF3F2E00)
val RedTertiaryContainerDark = Color(0xFF584414)
val RedOnTertiaryContainerDark = Color(0xFFFDE0A1)
val RedSurfaceDark = Color(0xFF201A19)
val RedOnSurfaceDark = Color(0xFFEDE0DE)
val RedSurfaceVariantDark = Color(0xFF534341)
val RedOnSurfaceVariantDark = Color(0xFFD8C2BF)
val RedOutlineDark = Color(0xFFA08C8A)
val RedInversePrimaryDark = Color(0xFFBA1A1A)
val RedInverseSurfaceDark = Color(0xFFEDE0DE)
val RedInverseOnSurfaceDark = Color(0xFF201A19)
