package com.xemophon.aljabr.ui.theme

import androidx.compose.ui.graphics.Color

// Default Purple Theme (Material 3 Defaults)
val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)
val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

// Calculator specific colors - Light (Base for overrides)
val CalcButtonStandardLight = Color(0xFFE2E2E6)
val CalcButtonOperationLight = Color(0xFFD2E4FF)
val CalcButtonEqualLight = Color(0xFFD3E0FF)
val CalcContainerBackgroundLight = Color(0xFFF1F0F4)
val CalcPrimaryFixedDimLight = Color(0xFFDDE2F9)

// Calculator specific colors - Dark (Base for overrides)
val CalcButtonStandardDark = Color(0xFF44474E)
val CalcButtonOperationDark = Color(0xFF00468B)
val CalcButtonEqualDark = Color(0xFF00468B)
val CalcContainerBackgroundDark = Color(0xFF1B1B1F)
val CalcPrimaryFixedDimDark = Color(0xFF404659)

// --- Blue Theme ---
// Light
val BluePrimaryLight = Color(0xFF005AC1)
val BlueOnPrimaryLight = Color(0xFFFFFFFF)
val BluePrimaryContainerLight = Color(0xFFD8E2FF)
val BlueOnPrimaryContainerLight = Color(0xFF001A41)
val BlueSecondaryLight = Color(0xFF535E78)
val BlueOnSecondaryLight = Color(0xFFFFFFFF)
val BlueSecondaryContainerLight = Color(0xFFD8E2FF)
val BlueOnSecondaryContainerLight = Color(0xFF0F1B32)
val BlueTertiaryLight = Color(0xFF6D5676)
val BlueOnTertiaryLight = Color(0xFFFFFFFF)
val BlueTertiaryContainerLight = Color(0xFFF7D8FF)
val BlueOnTertiaryContainerLight = Color(0xFF271430)
val BlueSurfaceLight = Color(0xFFFEFBFF)
val BlueOnSurfaceLight = Color(0xFF1B1B1F)
val BlueSurfaceVariantLight = Color(0xFFE1E2EC)
val BlueOnSurfaceVariantLight = Color(0xFF44474F)
val BlueOutlineLight = Color(0xFF74777F)
val BlueInversePrimaryLight = Color(0xFFADC6FF)
val BlueInverseSurfaceLight = Color(0xFF313033)
val BlueInverseOnSurfaceLight = Color(0xFFF4EFF4)

// Dark
val BluePrimaryDark = Color(0xFFADC6FF)
val BlueOnPrimaryDark = Color(0xFF002E69)
val BluePrimaryContainerDark = Color(0xFF004494)
val BlueOnPrimaryContainerDark = Color(0xFFD8E2FF)
val BlueSecondaryDark = Color(0xFFBBC6E4)
val BlueOnSecondaryDark = Color(0xFF253048)
val BlueSecondaryContainerDark = Color(0xFF3B465F)
val BlueOnSecondaryContainerDark = Color(0xFFD8E2FF)
val BlueTertiaryDark = Color(0xFFD9BDE3)
val BlueOnTertiaryDark = Color(0xFF3D2946)
val BlueTertiaryContainerDark = Color(0xFF543F5E)
val BlueOnTertiaryContainerDark = Color(0xFFF7D8FF)
val BlueSurfaceDark = Color(0xFF1B1B1F)
val BlueOnSurfaceDark = Color(0xFFE3E2E6)
val BlueSurfaceVariantDark = Color(0xFF44474F)
val BlueOnSurfaceVariantDark = Color(0xFFC4C6D0)
val BlueOutlineDark = Color(0xFF8E9099)
val BlueInversePrimaryDark = Color(0xFF005AC1)
val BlueInverseSurfaceDark = Color(0xFFE3E2E6)
val BlueInverseOnSurfaceDark = Color(0xFF1B1B1F)

// --- Green Theme ---
// Light
val GreenPrimaryLight = Color(0xFF006D3B)
val GreenOnPrimaryLight = Color(0xFFFFFFFF)
val GreenPrimaryContainerLight = Color(0xFF9BF6B4)
val GreenOnPrimaryContainerLight = Color(0xFF00210E)
val GreenSecondaryLight = Color(0xFF4F6354)
val GreenOnSecondaryLight = Color(0xFFFFFFFF)
val GreenSecondaryContainerLight = Color(0xFFD2E8D5)
val GreenOnSecondaryContainerLight = Color(0xFF0D1F13)
val GreenTertiaryLight = Color(0xFF3B6470)
val GreenOnTertiaryLight = Color(0xFFFFFFFF)
val GreenTertiaryContainerLight = Color(0xFFBEEAF7)
val GreenOnTertiaryContainerLight = Color(0xFF001F26)
val GreenSurfaceLight = Color(0xFFFBFDF8)
val GreenOnSurfaceLight = Color(0xFF191C1A)
val GreenSurfaceVariantLight = Color(0xFFDCE5DC)
val GreenOnSurfaceVariantLight = Color(0xFF404942)
val GreenOutlineLight = Color(0xFF707972)
val GreenInversePrimaryLight = Color(0xFF80D999)
val GreenInverseSurfaceLight = Color(0xFF2E312E)
val GreenInverseOnSurfaceLight = Color(0xFFF0F1EB)

// Dark
val GreenPrimaryDark = Color(0xFF80D999)
val GreenOnPrimaryDark = Color(0xFF00391C)
val GreenPrimaryContainerDark = Color(0xFF00522B)
val GreenOnPrimaryContainerDark = Color(0xFF9BF6B4)
val GreenSecondaryDark = Color(0xFFB7CCBA)
val GreenOnSecondaryDark = Color(0xFF213527)
val GreenSecondaryContainerDark = Color(0xFF384B3D)
val GreenOnSecondaryContainerDark = Color(0xFFD2E8D5)
val GreenTertiaryDark = Color(0xFFA2CEDC)
val GreenOnTertiaryDark = Color(0xFF003540)
val GreenTertiaryContainerDark = Color(0xFF214C58)
val GreenOnTertiaryContainerDark = Color(0xFFBEEAF7)
val GreenSurfaceDark = Color(0xFF191C1A)
val GreenOnSurfaceDark = Color(0xFFE1E3DF)
val GreenSurfaceVariantDark = Color(0xFF404942)
val GreenOnSurfaceVariantDark = Color(0xFFC0C9C0)
val GreenOutlineDark = Color(0xFF8A938B)
val GreenInversePrimaryDark = Color(0xFF006D3B)
val GreenInverseSurfaceDark = Color(0xFFE1E3DF)
val GreenInverseOnSurfaceDark = Color(0xFF191C1A)

// --- Red Theme ---
// Light
val RedPrimaryLight = Color(0xFFBA1A1A)
val RedOnPrimaryLight = Color(0xFFFFFFFF)
val RedPrimaryContainerLight = Color(0xFFFFDAD6)
val RedOnPrimaryContainerLight = Color(0xFF410002)
val RedSecondaryLight = Color(0xFF775652)
val RedOnSecondaryLight = Color(0xFFFFFFFF)
val RedSecondaryContainerLight = Color(0xFFFFDAD6)
val RedOnSecondaryContainerLight = Color(0xFF2C1512)
val RedTertiaryLight = Color(0xFF715B29)
val RedOnTertiaryLight = Color(0xFFFFFFFF)
val RedTertiaryContainerLight = Color(0xFFFDE0A1)
val RedOnTertiaryContainerLight = Color(0xFF251A00)
val RedSurfaceLight = Color(0xFFFFFBFF)
val RedOnSurfaceLight = Color(0xFF201A19)
val RedSurfaceVariantLight = Color(0xFFF5DDDA)
val RedOnSurfaceVariantLight = Color(0xFF534341)
val RedOutlineLight = Color(0xFF857371)
val RedInversePrimaryLight = Color(0xFFFFB4AB)
val RedInverseSurfaceLight = Color(0xFF362F2E)
val RedInverseOnSurfaceLight = Color(0xFFFBEEEC)

// Dark
val RedPrimaryDark = Color(0xFFFFB4AB)
val RedOnPrimaryDark = Color(0xFF690005)
val RedPrimaryContainerDark = Color(0xFF93000A)
val RedOnPrimaryContainerDark = Color(0xFFFFDAD6)
val RedSecondaryDark = Color(0xFFE7BDB8)
val RedOnSecondaryDark = Color(0xFF442926)
val RedSecondaryContainerDark = Color(0xFF5D3F3C)
val RedOnSecondaryContainerDark = Color(0xFFFFDAD6)
val RedTertiaryDark = Color(0xFFE0C38C)
val RedOnTertiaryDark = Color(0xFF3F2E00)
val RedTertiaryContainerDark = Color(0xFF584414)
val RedOnTertiaryContainerDark = Color(0xFFFDE0A1)
val RedSurfaceDark = Color(0xFF201A19)
val RedOnSurfaceDark = Color(0xFFEDE0DE)
val RedSurfaceVariantDark = Color(0xFF534341)
val RedOnSurfaceVariantDark = Color(0xFFD8C2BF)
val RedOutlineDark = Color(0xFFA08C8A)
val RedInversePrimaryDark = Color(0xFFBA1A1A)
val RedInverseSurfaceDark = Color(0xFFEDE0DE)
val RedInverseOnSurfaceDark = Color(0xFF201A19)

// --- Yellow Theme ---
// Light
val YellowPrimaryLight = Color(0xFF685F00)
val YellowOnPrimaryLight = Color(0xFFFFFFFF)
val YellowPrimaryContainerLight = Color(0xFFF7E569)
val YellowOnPrimaryContainerLight = Color(0xFF1E1C00)
val YellowSecondaryLight = Color(0xFF646042)
val YellowOnSecondaryLight = Color(0xFFFFFFFF)
val YellowSecondaryContainerLight = Color(0xFFEBE4BE)
val YellowOnSecondaryContainerLight = Color(0xFF1F1C05)
val YellowTertiaryLight = Color(0xFF406652)
val YellowOnTertiaryLight = Color(0xFFFFFFFF)
val YellowTertiaryContainerLight = Color(0xFFC2ECD3)
val YellowOnTertiaryContainerLight = Color(0xFF002114)
val YellowSurfaceLight = Color(0xFFFFFBEA)
val YellowOnSurfaceLight = Color(0xFF1D1B16)
val YellowSurfaceVariantLight = Color(0xFFE8E2D0)
val YellowOnSurfaceVariantLight = Color(0xFF4A4739)
val YellowOutlineLight = Color(0xFF7B7767)
val YellowInversePrimaryLight = Color(0xFFDAC950)
val YellowInverseSurfaceLight = Color(0xFF32302A)
val YellowInverseOnSurfaceLight = Color(0xFFF6F0E7)

// Dark
val YellowPrimaryDark = Color(0xFFDAC950)
val YellowOnPrimaryDark = Color(0xFF363100)
val YellowPrimaryContainerDark = Color(0xFF4E4700)
val YellowOnPrimaryContainerDark = Color(0xFFF7E569)
val YellowSecondaryDark = Color(0xFFCEC8A4)
val YellowOnSecondaryDark = Color(0xFF353118)
val YellowSecondaryContainerDark = Color(0xFF4C482C)
val YellowOnSecondaryContainerDark = Color(0xFFEBE4BE)
val YellowTertiaryDark = Color(0xFFA7D0B8)
val YellowOnTertiaryDark = Color(0xFF0E3726)
val YellowTertiaryContainerDark = Color(0xFF284E3B)
val YellowOnTertiaryContainerDark = Color(0xFFC2ECD3)
val YellowSurfaceDark = Color(0xFF15130E)
val YellowOnSurfaceDark = Color(0xFFE7E2D9)
val YellowSurfaceVariantDark = Color(0xFF4A4739)
val YellowOnSurfaceVariantDark = Color(0xFFCCC6B5)
val YellowOutlineDark = Color(0xFF959181)
val YellowInversePrimaryDark = Color(0xFF685F00)
val YellowInverseSurfaceDark = Color(0xFFE7E2D9)
val YellowInverseOnSurfaceDark = Color(0xFF32302A)

// --- Orange Theme ---
// Light
val OrangePrimaryLight = Color(0xFF8B5000)
val OrangeOnPrimaryLight = Color(0xFFFFFFFF)
val OrangePrimaryContainerLight = Color(0xFFFFDCC2)
val OrangeOnPrimaryContainerLight = Color(0xFF2E1500)
val OrangeSecondaryLight = Color(0xFF755846)
val OrangeOnSecondaryLight = Color(0xFFFFFFFF)
val OrangeSecondaryContainerLight = Color(0xFFFFDCC9)
val OrangeOnSecondaryContainerLight = Color(0xFF2B1609)
val OrangeTertiaryLight = Color(0xFF5E6135)
val OrangeOnTertiaryLight = Color(0xFFFFFFFF)
val OrangeTertiaryContainerLight = Color(0xFFE3E6AF)
val OrangeOnTertiaryContainerLight = Color(0xFF1B1D00)
val OrangeSurfaceLight = Color(0xFFFFF8F5)
val OrangeOnSurfaceLight = Color(0xFF221A14)
val OrangeSurfaceVariantLight = Color(0xFFF4DFD3)
val OrangeOnSurfaceVariantLight = Color(0xFF52443C)
val OrangeOutlineLight = Color(0xFF85746B)
val OrangeInversePrimaryLight = Color(0xFFFFB77C)
val OrangeInverseSurfaceLight = Color(0xFF382E28)
val OrangeInverseOnSurfaceLight = Color(0xFFFFEEE5)

// Dark
val OrangePrimaryDark = Color(0xFFFFB77C)
val OrangeOnPrimaryDark = Color(0xFF4A2800)
val OrangePrimaryContainerDark = Color(0xFF693C00)
val OrangeOnPrimaryContainerDark = Color(0xFFFFDCC2)
val OrangeSecondaryDark = Color(0xFFE5C0AB)
val OrangeOnSecondaryDark = Color(0xFF422B1C)
val OrangeSecondaryContainerDark = Color(0xFF5B4130)
val OrangeOnSecondaryContainerDark = Color(0xFFFFDCC9)
val OrangeTertiaryDark = Color(0xFFC7CA95)
val OrangeOnTertiaryDark = Color(0xFF30330B)
val OrangeTertiaryContainerDark = Color(0xFF46491F)
val OrangeOnTertiaryContainerDark = Color(0xFFE3E6AF)
val OrangeSurfaceDark = Color(0xFF19120C)
val OrangeOnSurfaceDark = Color(0xFFF0DFD7)
val OrangeSurfaceVariantDark = Color(0xFF52443C)
val OrangeOnSurfaceVariantDark = Color(0xFFD7C3B7)
val OrangeOutlineDark = Color(0xFFA08D83)
val OrangeInversePrimaryDark = Color(0xFF8B5000)
val OrangeInverseSurfaceDark = Color(0xFFF0DFD7)
val OrangeInverseOnSurfaceDark = Color(0xFF382E28)

// --- Teal Theme ---
// Light
val TealPrimaryLight = Color(0xFF006A6A)
val TealOnPrimaryLight = Color(0xFFFFFFFF)
val TealPrimaryContainerLight = Color(0xFF9CF1F0)
val TealOnPrimaryContainerLight = Color(0xFF002020)
val TealSecondaryLight = Color(0xFF4A6363)
val TealOnSecondaryLight = Color(0xFFFFFFFF)
val TealSecondaryContainerLight = Color(0xFFCCE8E7)
val TealOnSecondaryContainerLight = Color(0xFF051F1F)
val TealTertiaryLight = Color(0xFF4B607C)
val TealOnTertiaryLight = Color(0xFFFFFFFF)
val TealTertiaryContainerLight = Color(0xFFD3E4FF)
val TealOnTertiaryContainerLight = Color(0xFF041C35)
val TealSurfaceLight = Color(0xFFF4FAFA)
val TealOnSurfaceLight = Color(0xFF161D1D)
val TealSurfaceVariantLight = Color(0xFFDAE5E4)
val TealOnSurfaceVariantLight = Color(0xFF3F4948)
val TealOutlineLight = Color(0xFF6F7979)
val TealInversePrimaryLight = Color(0xFF80D5D4)
val TealInverseSurfaceLight = Color(0xFF2B3131)
val TealInverseOnSurfaceLight = Color(0xFFECF2F1)

// Dark
val TealPrimaryDark = Color(0xFF80D5D4)
val TealOnPrimaryDark = Color(0xFF003737)
val TealPrimaryContainerDark = Color(0xFF004F4F)
val TealOnPrimaryContainerDark = Color(0xFF9CF1F0)
val TealSecondaryDark = Color(0xFFB0CCCB)
val TealOnSecondaryDark = Color(0xFF1B3534)
val TealSecondaryContainerDark = Color(0xFF324B4B)
val TealOnSecondaryContainerDark = Color(0xFFCCE8E7)
val TealTertiaryDark = Color(0xFFB3C8E8)
val TealOnTertiaryDark = Color(0xFF1C324B)
val TealTertiaryContainerDark = Color(0xFF334863)
val TealOnTertiaryContainerDark = Color(0xFFD3E4FF)
val TealSurfaceDark = Color(0xFF0E1415)
val TealOnSurfaceDark = Color(0xFFE0E3E3)
val TealSurfaceVariantDark = Color(0xFF3F4948)
val TealOnSurfaceVariantDark = Color(0xFFBEC9C8)
val TealOutlineDark = Color(0xFF889392)
val TealInversePrimaryDark = Color(0xFF006A6A)
val TealInverseSurfaceDark = Color(0xFFE0E3E3)
val TealInverseOnSurfaceDark = Color(0xFF2B3131)

// --- Pink Theme ---
// Light
val PinkPrimaryLight = Color(0xFF984061)
val PinkOnPrimaryLight = Color(0xFFFFFFFF)
val PinkPrimaryContainerLight = Color(0xFFFFD9E2)
val PinkOnPrimaryContainerLight = Color(0xFF3E001D)
val PinkSecondaryLight = Color(0xFF74565F)
val PinkOnSecondaryLight = Color(0xFFFFFFFF)
val PinkSecondaryContainerLight = Color(0xFFFFD9E2)
val PinkOnSecondaryContainerLight = Color(0xFF2B151C)
val PinkTertiaryLight = Color(0xFF7C5635)
val PinkOnTertiaryLight = Color(0xFFFFFFFF)
val PinkTertiaryContainerLight = Color(0xFFFFDCC1)
val PinkOnTertiaryContainerLight = Color(0xFF2E1500)
val PinkSurfaceLight = Color(0xFFFFF8F8)
val PinkOnSurfaceLight = Color(0xFF201A1B)
val PinkSurfaceVariantLight = Color(0xFFF2DDE1)
val PinkOnSurfaceVariantLight = Color(0xFF514347)
val PinkOutlineLight = Color(0xFF837377)
val PinkInversePrimaryLight = Color(0xFFFFB0C8)
val PinkInverseSurfaceLight = Color(0xFF362E30)
val PinkInverseOnSurfaceLight = Color(0xFFFAEEEE)

// Dark
val PinkPrimaryDark = Color(0xFFFFB0C8)
val PinkOnPrimaryDark = Color(0xFF5E1133)
val PinkPrimaryContainerDark = Color(0xFF7B2949)
val PinkOnPrimaryContainerDark = Color(0xFFFFD9E2)
val PinkSecondaryDark = Color(0xFFE2BDC6)
val PinkOnSecondaryDark = Color(0xFF422931)
val PinkSecondaryContainerDark = Color(0xFF5B3F47)
val PinkOnSecondaryContainerDark = Color(0xFFFFD9E2)
val PinkTertiaryDark = Color(0xFFEFBD94)
val PinkOnTertiaryDark = Color(0xFF47290C)
val PinkTertiaryContainerDark = Color(0xFF613F20)
val PinkOnTertiaryContainerDark = Color(0xFFFFDCC1)
val PinkSurfaceDark = Color(0xFF181113)
val PinkOnSurfaceDark = Color(0xFFECE0E1)
val PinkSurfaceVariantDark = Color(0xFF514347)
val PinkOnSurfaceVariantDark = Color(0xFFD5C2C6)
val PinkOutlineDark = Color(0xFF9E8C90)
val PinkInversePrimaryDark = Color(0xFF984061)
val PinkInverseSurfaceDark = Color(0xFFECE0E1)
val PinkInverseOnSurfaceDark = Color(0xFF201A1B)

// --- Brown Theme ---
// Light
val BrownPrimaryLight = Color(0xFF7A5930)
val BrownOnPrimaryLight = Color(0xFFFFFFFF)
val BrownPrimaryContainerLight = Color(0xFFFFDCC1)
val BrownOnPrimaryContainerLight = Color(0xFF2A1700)
val BrownSecondaryLight = Color(0xFF6C5D4F)
val BrownOnSecondaryLight = Color(0xFFFFFFFF)
val BrownSecondaryContainerLight = Color(0xFFF6E0CE)
val BrownOnSecondaryContainerLight = Color(0xFF241A0F)
val BrownTertiaryLight = Color(0xFF596249)
val BrownOnTertiaryLight = Color(0xFFFFFFFF)
val BrownTertiaryContainerLight = Color(0xFFDDDCA8)
val BrownOnTertiaryContainerLight = Color(0xFF171E0B)
val BrownSurfaceLight = Color(0xFFFFF8F5)
val BrownOnSurfaceLight = Color(0xFF201B17)
val BrownSurfaceVariantLight = Color(0xFFF0E0D2)
val BrownOnSurfaceVariantLight = Color(0xFF4F453B)
val BrownOutlineLight = Color(0xFF81756A)
val BrownInversePrimaryLight = Color(0xFFECBE91)
val BrownInverseSurfaceLight = Color(0xFF362F2B)
val BrownInverseOnSurfaceLight = Color(0xFFFAEEE8)

// Dark
val BrownPrimaryDark = Color(0xFFECBE91)
val BrownOnPrimaryDark = Color(0xFF462A06)
val BrownPrimaryContainerDark = Color(0xFF60411B)
val BrownOnPrimaryContainerDark = Color(0xFFFFDCC1)
val BrownSecondaryDark = Color(0xFFD9C4B3)
val BrownOnSecondaryDark = Color(0xFF3B2F23)
val BrownSecondaryContainerDark = Color(0xFF534538)
val BrownOnSecondaryContainerDark = Color(0xFFF6E0CE)
val BrownTertiaryDark = Color(0xFFC1CA8D)
val BrownOnTertiaryDark = Color(0xFF2C331E)
val BrownTertiaryContainerDark = Color(0xFF424A33)
val BrownOnTertiaryContainerDark = Color(0xFFDDDCA8)
val BrownSurfaceDark = Color(0xFF17130F)
val BrownOnSurfaceDark = Color(0xFFECE0DA)
val BrownSurfaceVariantDark = Color(0xFF4F453B)
val BrownOnSurfaceVariantDark = Color(0xFFD3C4B7)
val BrownOutlineDark = Color(0xFF9C8E83)
val BrownInversePrimaryDark = Color(0xFF7A5930)
val BrownInverseSurfaceDark = Color(0xFFECE0DA)
val BrownInverseOnSurfaceDark = Color(0xFF201B17)